package wagony.cechyWagonu;

public enum RodzajDostepnejKuchni {

    KUCHNIA_WLOSKA, KUCHNIA_POLSKA, KUCHNIA_CHINSKA, KUCHNIA_INDYJSKA, KUCHNIA_JAPONSKA, KUCHNIA_FRANCUSKA, KUCHNIA_AMERYKANSKA, BRAK_INFORMACJI
}
